# -*- coding: utf-8 -*-
"""HRData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxZ-qoE6kV0I6eucyaf1987tN2Ru32T_
"""

import pandas as pd

# Loading the dataset
df = pd.read_csv('HRData.csv')

# Deleting Age, Attrition , DailyRate
columns_to_drop = ['Age', 'Attrition', 'DailyRate']
df.drop(columns=columns_to_drop, inplace=True)

# Renaming columns
Col_rename = {
    'BusinessTravel': 'Travel for Business',
    'EmployeeNumber': 'Emp ID',
    'DistanceFromHome': 'Distance'
}
df.rename(columns=Col_rename, inplace=True)

# Eliminating redundant entries
df.drop_duplicates(inplace=True)

# Sanitizing  columns
df['Department'] = df['Department'].str.strip().str.upper()
df['Travel for Business'] = df['Travel for Business'].str.strip().str.upper()

# Eliminating NaN values
df.dropna(inplace=True)

# Changing the data type of Column from int to float
df['HourlyRate'] = df['HourlyRate'].astype(float)


# Saving the cleaned dataset
df.to_csv('cleaned_hr_data.csv', index=False)

