# -*- coding: utf-8 -*-
"""SalesData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxZ-qoE6kV0I6eucyaf1987tN2Ru32T_
"""

import pandas as pd
import matplotlib.pyplot as plt
# Load the data from CSV
df = pd.read_csv('ECOMM DATA.csv')

# Convert Order Date to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])

# Compute total sales
total_sales = df['Quantity'].sum()
print(total_sales)
# Analyze sales trends over time
sales_by_date = df.groupby(df['Order Date'].dt.date)['Quantity'].sum()

# Determine best-selling products
best_selling_products = df.groupby('Product Name')['Quantity'].sum().sort_values(ascending=False).head(10)
print(best_selling_products)

#Total sales over time
plt.figure(figsize=(10, 6))
plt.plot(sales_by_date.index, sales_by_date.values, label='Total Sales')
plt.xlabel('Date')
plt.ylabel('Total Sales')
plt.title('Total Sales Over Time')
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Best-selling products
plt.figure(figsize=(10, 6))
best_selling_products.plot(kind='bar', color='skyblue')
plt.xlabel('Product')
plt.ylabel('Quantity Ordered')
plt.title('Best-Selling Products')
plt.tight_layout()
plt.show()

